### ISSUE TITLE
Add support for markdown tables

### ISSUE THREAD

**Issue by bachase** [vinniefalco/docca#14]
Doxygen supports markdown style [tables](https://www.stack.nl/~dimitri/doxygen/manual/markdown.html#md_tables), but docca is not transforming them into HTML tables.

For example, updating https://github.com/ripple/rippled/blob/develop/src/ripple/test/BasicNetwork.h#L85-L94 to the markdown style renders as
![docca](https://cloud.githubusercontent.com/assets/14430/21029568/5c5eb31a-bd68-11e6-8b2e-c6b991e225ea.PNG)

but native doxygen renders as

![doxygen](https://cloud.githubusercontent.com/assets/14430/21029584/7347e81c-bd68-11e6-88aa-82772b349a17.PNG)

**Comment by vinniefalco** [comment]
Oh that looks lovely
