### ISSUE TITLE
Direct fetching of that commit failed

### ISSUE THREAD

**Issue by rcorbin2018** [vinniefalco/docca#37]
Trying to build rippled and got the following today 9/16/2019:

error: Server does not allow request for unadvertised object 335dbf9c3613e997ed56d540cc8c5ff2e28cab2d
Fetched in submodule path 'doc/docca', but it did not contain 335dbf9c3613e997ed56d540cc8c5ff2e28cab2d. Direct fetching of that commit failed.

Did the above docca commit object exist before and is gone now? What am I missing?

Thanks.

-Rob

**Comment by rcorbin2018** [comment]
I can see the commit when I click the link in my comment above, but that commit is not showing up as a tree in the commits tab. After I clone the project, I run:

git checkout 335dbf9c3613e997ed56d540cc8c5ff2e28cab2d
fatal: reference is not a tree: 335dbf9c3613e997ed56d540cc8c5ff2e28cab2d

Is this tree being hidden by permissions or something?

Thanks.

**Comment by vinniefalco** [comment]
Does rippled even use **docca** anymore? I rewrote the branch, which is why you can't find the commit. Where does rippled use docca?

**Comment by rcorbin2018** [comment]
rippled uses NuDB which uses docca as a submodule. When building rippled from source, it does a git clone on NuDB and it’s sub modules.

Thanks.

**Comment by vinniefalco** [comment]
Yeah, I forgot that NuDB used docca in a submodule. I have restored the branch that was removed, so if you try again it should work.

**Comment by rcorbin2018** [comment]
It's working now.

Thank you. I appreciate it.
